# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  blazorwebappdocker:
    image: blazorwebappdocker
    build:
      context: .
      dockerfile: Blazor-WebApp-Docker/Dockerfile
    ports:
      - 5136:5136
